### ISSUE TITLE
MLT19 datasets

### ISSUE THREAD

**Issue by hagerwang** [mxin262/ESTextSpotter#4]
The MLT19 dataset was not found in SPTS v2, hope you can upload this part of the dataset in the format corresponding to your code, please.

![cf9f1bd93782297d320f70daec49f9d](https://github.com/mxin262/ESTextSpotter/assets/56829690/b30281f5-9960-43eb-b1d8-ace970693e82)

**Comment by mxin262** [comment]
The link is updated in Readme.

**Comment by hagerwang** [comment]
> The link is updated in Readme.

非常感谢
