### ISSUE TITLE
Can I train ESTextSpotter-Polygon without Bezier curves?

### ISSUE THREAD

**Issue by ku21fan** [mxin262/ESTextSpotter#7]
Hi, first of all, thank you for providing the exciting work and code!

Currently, I am trying to use ESTS for my project.
I need to compare ESTextSpotter-Bezier and ESTextSpotter-Polygon (like Table 3 in the ESTS paper). 

I tried to train ESTS without Bezier curves, and I found that some essential codes (e.g. ESTextSpotter/models/ests/ests.py) depend on Bezier curves.

Can I train ESTextSpotter-Polygon without Bezier curves? 
Is there a code for it? Or can you provide some tips or hints for it?

Best regards,

**Comment by mxin262** [comment]
Hi, for ESTextSpotter-Polygon, we used Bezier curves to generate the polygon. You can also generate the polygon following the [TextBPN](https://github.com/GXYM/TextBPN-Plus-Plus/tree/main).

**Comment by ku21fan** [comment]
Thank you for your reply!

Unfortunately, it seems there is no easy way to train ESTS without Bezier curves... 
As you did, I will use Bezier curves to generate the polygon.
Thanks!
