### ISSUE TITLE
How to get the evaluate results of VinText?

### ISSUE THREAD

**Issue by TongkunGuan** [mxin262/ESTextSpotter#8]
Hi! I meet an issue~
When I try to evaluate the result of VinText, I found [text_evaluation_all.py] did not provide the code for VinText.

**Comment by TongkunGuan** [comment]
![image](https://github.com/mxin262/ESTextSpotter/assets/51256562/cfdd4174-dc69-4dc6-b870-57130d8597d6)
When I use the checkpoint for VinText evaluation, for detection, I get 89.56 hmean.
![image](https://github.com/mxin262/ESTextSpotter/assets/51256562/e00f7e1a-ae85-42d5-9355-5841005359e5)
But for spotting, I get 24 hmean. Why?

**Comment by mxin262** [comment]
Hi! You can  You can refer to this [file](https://github.com/mxin262/SwinTextSpotter/blob/main/detectron2/evaluation/text_evaluation.py).  I will also update the evaluation in this repository later (Expected next week). As with the official open-source code, the recognition of this dataset requires post-processing
