### ISSUE TITLE
The roi feature's shape in paper

### ISSUE THREAD

**Issue by pd162** [mxin262/ESTextSpotter#9]
Thanks for your outstanding work! I found that the sampling feature in Sec3.2 can be represented $F_p  \in \mathcal{R}^{N \times H \times T \times C}$. However, I cannot find the definition of H. After running your code, I think the dimension shape of $F_p$ should be $\mathcal{R}^{N \times T \times C}$, corresponding to Sec. 3.3. I look forward to your further discussion!

**Comment by mxin262** [comment]
Hi! As shown in Sec 3.2, we sample the features $F_p  \in \mathcal{R}^{N \times H \times T \times C}$ from the proposals and average them over the height dimension to initialize recognition queries.  After averaging, the shape of $F_p$ becomes $\mathcal{R}^{N \times 1 \times T \times C}$. Subsequently, we reshape it into $\mathcal{R}^{N  \times T \times C}$.

**Comment by pd162** [comment]
> Hi! As shown in Sec 3.2, we sample the features Fp∈RN×H×T×C from the proposals and average them over the height dimension to initialize recognition queries. After averaging, the shape of Fp becomes RN×1×T×C. Subsequently, we reshape it into RN×T×C.

Thanks for your reply, I think I get it!
